steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.ingestion
      - -t
      - gcr.io/$PROJECT_ID/cloud-monitored-rag-ingestion:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/cloud-monitored-rag-ingestion:latest
images:
  - gcr.io/$PROJECT_ID/cloud-monitored-rag-ingestion:latest
