steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.api
      - -t
      - gcr.io/$PROJECT_ID/cloud-monitored-rag-api:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/cloud-monitored-rag-api:latest
images:
  - gcr.io/$PROJECT_ID/cloud-monitored-rag-api:latest
